server:
  port: 8768
spring:
  application:
    name: greeting-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://ci-server:3306/datebook?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    # Hikari will use the above plus the following to setup connection pooling
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  rabbitmq:
    host: ci-server
    port: 5672
    username: chenshun
    password: 123456
#
eureka:
  client:
    service-url:
      defaultZone: http://peer1:1111/eureka/,http://peer2:2222/eureka/
    fetch-registry: true
    registry-fetch-interval-seconds: 30
#
logging:
  config: logback-service.xml
