server:
  port: 8080
spring:
  application:
    name: zuul-server
  profiles:
    active: dev
logging:
  config: classpath:logback-zuulserver.xml
#
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:1111/eureka/
    fetch-registry: true
    registry-fetch-interval-seconds: 30
#
management:
  endpoints:
    web:
      exposure:
        # 端外暴露的端点，使用 "*" 表示暴露所有的端点，bus-refresh 默认是不暴露的
        include: "*"
        exclude: env,beans
#
zuul:
  # 重试机制失败
  retryable: true
  # 忽略的路由路径，指定访问的路由路径除外
  ignored-services: '*'
  routes:
    say-hello-service:
      path: /say-hello-service/**
      serviceId: say-hello-service
    greeting-service:
      path: /greeting-service/**
      serviceId: greeting-service