server:
  port: 1121
spring:
  application:
    name: greeting-service
  profiles:
    active: dev
#
feign:
  hystrix:
    enabled: true
#
eureka:
  client:
    service-url:
      defaultZone: http://192.168.139.132:1111/eureka/
    fetch-registry: true
    registry-fetch-interval-seconds: 30
#
logging:
  config: classpath:logback-service.xml
#
defaultName: defaultName
