server:
  port: 8080
logging:
  config: classpath:logback-service.xml
#
spring:
  profiles:
    active: dev
  application:
    name: say-hello-service
  zipkin:
    # Zipkin 访问地址
    base-url: http://zipkin:9411
  sleuth:
    sampler:
      # 抽样百分比，开发环境可以设置为 1 也就是 100%
      probability: 1
#
eureka:
  client:
    service-url:
      # 指定注册中心地址
      defaultZone: http://eureka-server:1111/eureka/
    fetch-registry: true
    registry-fetch-interval-seconds: 30