server:
  port: 1111
spring:
  application:
    name: eureka-server
#
eureka:
  instance:
    # 设置当前 Eureka 注册中心地址，否则将会从当前所处的操作系统进行推测
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    registry-fetch-interval-seconds: 30
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
